-- Allow one-decimal product prices.
ALTER TABLE "Product"
  ALTER COLUMN "cost" TYPE DOUBLE PRECISION USING "cost"::DOUBLE PRECISION,
  ALTER COLUMN "cost2" TYPE DOUBLE PRECISION USING "cost2"::DOUBLE PRECISION,
  ALTER COLUMN "cost3" TYPE DOUBLE PRECISION USING "cost3"::DOUBLE PRECISION,
  ALTER COLUMN "price" TYPE DOUBLE PRECISION USING "price"::DOUBLE PRECISION;
