-- 상품 단가와 한줄장부 금액에 소수점 한 자리 값을 저장할 수 있도록 변경
ALTER TABLE "Product"
  ALTER COLUMN "cost" TYPE DOUBLE PRECISION USING "cost"::DOUBLE PRECISION,
  ALTER COLUMN "cost2" TYPE DOUBLE PRECISION USING "cost2"::DOUBLE PRECISION,
  ALTER COLUMN "cost3" TYPE DOUBLE PRECISION USING "cost3"::DOUBLE PRECISION,
  ALTER COLUMN "price" TYPE DOUBLE PRECISION USING "price"::DOUBLE PRECISION;

ALTER TABLE "WholesaleLedger"
  ALTER COLUMN "purchaseAmount" TYPE DOUBLE PRECISION USING "purchaseAmount"::DOUBLE PRECISION,
  ALTER COLUMN "saleAmount" TYPE DOUBLE PRECISION USING "saleAmount"::DOUBLE PRECISION,
  ALTER COLUMN "shippingFee" TYPE DOUBLE PRECISION USING "shippingFee"::DOUBLE PRECISION;
